runtime: nodejs20
env: standard
instance_class: F1

automatic_scaling:
  min_idle_instances: automatic
  max_idle_instances: automatic
  min_pending_latency: automatic
  max_pending_latency: automatic

env_variables:
  MONGO_URI: "mongodb+srv://omer12899:<aa1234>@recepieweb.tq7l6.mongodb.net/?retryWrites=true&w=majority&appName=RecepieWeb"
  JWT_SECRET: "7b52196084261a422618418793b06e6fb10a0c4a1811e71a4a56ea1bb6409e37f6e94525a582286b794394c0fd385215b33de04c4f80a2c6507f7e982fa31d8d"
  # Add any other environment variables your app needs
